/* Generated By:JavaCC: Do not edit this line. ListParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ListParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COM = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int LCP = 10;
  /** RegularExpression Id. */
  int POWER = 11;
  /** RegularExpression Id. */
  int RCP = 12;
  /** RegularExpression Id. */
  int LCL = 13;
  /** RegularExpression Id. */
  int LCR = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int NUM = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"^\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"x\"",
    "<NUM>",
  };

}
